# Generated by Django 4.2.21 on 2025-07-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_alter_tenantmodel_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenPlanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("total_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Token Plan",
                "verbose_name_plural": "Token Plans",
            },
        ),
        migrations.CreateModel(
            name="TokenLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("consume", "Consume"),
                            ("recharge", "Recharge"),
                            ("reset", "Reset"),
                            ("adjust", "Adjust"),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Cantidad de tokens involucrados en la transaccion"
                    ),
                ),
                (
                    "total_remaining",
                    models.IntegerField(
                        help_text="Balance restante despues de la operacion"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")], max_length=3
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_ledgers",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Ledger",
                "verbose_name_plural": "Token Ledgers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantQuotaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("last_reset", models.DateField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="quota.tokenplanmodel",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_quota",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Quota",
                "verbose_name_plural": "Tenant Quotas",
            },
        ),
    ]
