# Generated by Django 4.2.21 on 2025-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantquotamodel",
            name="plan_exceeded",
            field=models.BooleanField(default=False),
        ),
    ]
