# Generated by Django 4.2.21 on 2025-07-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quota", "0002_tenantquotamodel_plan_exceeded"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenledgermodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Token Transaction Ledger",
                "verbose_name_plural": "Token Transaction Ledgers",
            },
        ),
    ]
