# Generated by Django 4.2.21 on 2025-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_agentmodel_agent_model_id_agentmodel_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmodel",
            name="description",
            field=models.TextField(
                blank=True,
                default="Agente creado para responder preguntas y realizar tareas específicas.",
                help_text="Descripción del agente, opcional",
                null=True,
            ),
        ),
    ]
