# Generated by Django 4.2.21 on 2025-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        ("agents", "0004_agentmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmodel",
            name="api_call_models",
            field=models.ManyToManyField(blank=True, to="tools.apicallmodel"),
        ),
    ]
