# Generated by Django 4.2.21 on 2025-06-23 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agentmodel_api_call_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmodel",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Número máximo de tokens a predecir en la respuesta del agente",
            ),
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Controla la aleatoriedad de las respuestas del agente (0.0 a 1.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="agentmodel",
            name="top_p",
            field=models.FloatField(
                default=0.9,
                help_text="Controla la diversidad de las respuestas del agente (0.0 a 1.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
