# Generated by Django 4.2.21 on 2025-07-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_sentimentagentmodel"),
        ("agents", "0006_agentmodel_max_tokens_agentmodel_temperature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmodel",
            name="analize_sentiment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Agente de análisis de sentimientos asociado al agente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="analysis.sentimentagentmodel",
            ),
        ),
    ]
