# Generated by Django 5.2.1 on 2025-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_knowledgemodel_delete_knowledgepdfmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgemodel",
            name="category",
            field=models.CharField(
                choices=[("plain_document", "plain_document"), ("website", "website")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgemodel",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="knowledgemodel",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="knowledgemodel",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
