# Generated by Django 4.2.21 on 2025-06-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantmodel_ai_token_tenantmodel_cwu_token"),
        ("knowledge", "0004_alter_knowledgemodel_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Tenant asociado a este modelo de conocimiento",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_models",
                to="tenants.tenantmodel",
            ),
        ),
    ]
