# Generated by Django 4.2.21 on 2025-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_knowledgemodel_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemodel",
            name="recreate",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el modelo de conocimiento necesita ser recreado",
            ),
        ),
    ]
