# Generated by Django 4.2.21 on 2025-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0006_knowledgemodel_recreate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgemodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("plain_document", "plain_document"),
                    ("website", "website"),
                    ("document", "document"),
                ],
                max_length=50,
            ),
        ),
    ]
