# Generated by Django 4.2.21 on 2025-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_alter_knowledgemodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemodel",
            name="path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
