# Generated by Django 4.2.21 on 2025-06-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("knowledge", "0008_knowledgemodel_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgemodel",
            name="path",
        ),
        migrations.AddField(
            model_name="knowledgemodel",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento asociado a este modelo de conocimiento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_models",
                to="documents.documentmodel",
            ),
        ),
    ]
