# Generated by Django 4.2.21 on 2025-06-15 02:05

from django.db import migrations, models

import tenants.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmodel",
            name="ai_token",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Token de AI",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantmodel",
            name="cwu_token",
            field=models.CharField(
                default=tenants.helpers.generate_cwu_token,
                help_text="Token único del tenant que comienza con 'cwu_'",
                max_length=36,
            ),
        ),
    ]
