# Generated by Django 4.2.21 on 2025-06-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmodel",
            name="model",
            field=models.CharField(
                choices=[("ollama", "OLLAMA"), ("gemini", "GEMINI")],
                default="ollama",
                max_length=50,
            ),
        ),
    ]
