# Generated by Django 4.2.21 on 2025-06-18 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Título descriptivo del documento", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del documento",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo del documento",
                        upload_to=documents.models.user_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "csv",
                                    "xlsx",
                                    "xls",
                                    "json",
                                    "md",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word Document"),
                            ("docx", "Word Document (DOCX)"),
                            ("txt", "Text File"),
                            ("csv", "CSV File"),
                            ("xlsx", "Excel File"),
                            ("xls", "Excel File (XLS)"),
                            ("json", "JSON File"),
                            ("md", "Markdown File"),
                        ],
                        help_text="Tipo de documento",
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        editable=False, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        editable=False,
                        help_text="Nombre original del archivo",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica si el documento está activo"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el documento ha sido procesado",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se procesó el documento",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant al que pertenece el documento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.tenantmodel",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="Usuario que subió el documento",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "uploaded_by"],
                        name="documents_d_tenant__256ead_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="documents_d_documen_01135d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="documents_d_is_acti_c0b1e6_idx"
                    ),
                ],
            },
        ),
    ]
