# Generated by Django 4.2.21 on 2025-06-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document (DOCX)"),
                    ("txt", "Text File"),
                    ("csv", "CSV File"),
                    ("json", "JSON File"),
                    ("md", "Markdown File"),
                ],
                help_text="Tipo de documento",
                max_length=10,
            ),
        ),
    ]
