# Generated by Django 4.2.21 on 2025-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_documentmodel_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document (DOCX)"),
                    ("doc", "Word Document (DOC)"),
                    ("txt", "Text File"),
                    ("csv", "CSV File"),
                    ("json", "JSON File"),
                    ("md", "Markdown File"),
                    ("xlsx", "Excel (XLSX)"),
                    ("xls", "Excel (XLS)"),
                ],
                help_text="Tipo de documento (se detecta automáticamente)",
                max_length=10,
            ),
        ),
    ]
