# Generated by Django 4.2.21 on 2025-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_documentmodel_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF"),
                    ("doc", "Word Document (DOC)"),
                    ("docx", "Word Document (DOCX)"),
                    ("txt", "Text File"),
                    ("csv", "CSV File"),
                    ("xlsx", "Excel File (XLSX)"),
                    ("xls", "Excel File (XLS)"),
                    ("json", "JSON File"),
                    ("md", "Markdown File"),
                ],
                help_text="Tipo de documento (se detecta automáticamente si no se especifica)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="documentmodel",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Tamaño del archivo en bytes"
            ),
        ),
        migrations.AlterField(
            model_name="documentmodel",
            name="original_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Nombre original del archivo",
                max_length=255,
            ),
        ),
    ]
