# Generated by Django 4.2.21 on 2025-07-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0007_agentmodel_analize_sentiment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramCommunicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        help_text="Token de acceso del bot de Telegram",
                        max_length=255,
                        verbose_name="Token de Telegram",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        help_text="Nombre del bot de Telegram",
                        max_length=255,
                        verbose_name="Nombre del bot de Telegram",
                    ),
                ),
                (
                    "voice",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el bot puede enviar mensajes de voz",
                        verbose_name="Enviar mensajes de voz",
                    ),
                ),
                (
                    "files",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el bot puede enviar archivos",
                        verbose_name="Enviar archivos",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agente asociado al bot de Telegram",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_communication",
                        to="agents.agentmodel",
                        verbose_name="Agente",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
