# Generated by Django 4.2.21 on 2025-07-08 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="ID del chat de Telegram", unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "type",
                    models.CharField(
                        help_text="Tipo de chat (private, group, etc)", max_length=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="ID de usuario de Telegram", unique=True
                    ),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramMessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update_id",
                    models.BigIntegerField(help_text="ID de actualización de Telegram"),
                ),
                (
                    "message_id",
                    models.BigIntegerField(help_text="ID del mensaje de Telegram"),
                ),
                (
                    "telegram_datetime",
                    models.DateTimeField(
                        help_text="Fecha del mensaje (timestamp de Telegram)"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Texto del mensaje", null=True
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Chat al que pertenece el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.telegramchatmodel",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="Usuario que envía el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_from",
                        to="communication.telegramusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
