# Generated by Django 4.2.21 on 2025-07-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_telegramchatmodel_telegramusermodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="message_id",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="telegram_datetime",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="text",
        ),
        migrations.AlterField(
            model_name="telegrammessagemodel",
            name="update_id",
            field=models.BigIntegerField(
                help_text="ID de actualización de Telegram", unique=True
            ),
        ),
        migrations.CreateModel(
            name="TelegramMessageMessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_id",
                    models.BigIntegerField(
                        help_text="ID del mensaje de Telegram", unique=True
                    ),
                ),
                (
                    "telegram_date",
                    models.DateTimeField(
                        help_text="Fecha y hora del mensaje en Telegram",
                        verbose_name="Fecha del mensaje de Telegram",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Texto del mensaje de Telegram",
                        verbose_name="Texto del mensaje de Telegram",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Chat de Telegram al que pertenece el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.telegramchatmodel",
                        verbose_name="Chat de Telegram",
                    ),
                ),
                (
                    "telegram_from_user",
                    models.ForeignKey(
                        help_text="Usuario que envió el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.telegramusermodel",
                        verbose_name="Usuario de Telegram",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="telegrammessagemodel",
            name="message",
            field=models.ForeignKey(
                default=None,
                help_text="Mensaje de Telegram asociado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communication.telegrammessagemessagemodel",
                verbose_name="Mensaje de Telegram",
            ),
            preserve_default=False,
        ),
    ]
