# Generated by Django 4.2.21 on 2025-07-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_remove_telegrammessagemodel_chat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramFromModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_id",
                    models.BigIntegerField(
                        help_text="ID de usuario de Telegram", unique=True
                    ),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="telegrammessagemessagemodel",
            name="telegram_from_user",
        ),
        migrations.DeleteModel(
            name="TelegramUserModel",
        ),
        migrations.AddField(
            model_name="telegrammessagemessagemodel",
            name="telegram_from",
            field=models.ForeignKey(
                default=None,
                help_text="Usuario que envió el mensaje",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communication.telegramfrommodel",
                verbose_name="Usuario de Telegram",
            ),
            preserve_default=False,
        ),
    ]
