# Generated by Django 4.2.21 on 2025-07-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0004_telegramfrommodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessagemessagemodel",
            name="telegram_date",
        ),
    ]
