# Generated by Django 4.2.21 on 2025-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0005_remove_telegrammessagemessagemodel_telegram_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrammessagemessagemodel",
            name="telegram_date",
            field=models.IntegerField(
                default=None,
                help_text="Fecha y hora del mensaje en Telegram",
                verbose_name="Fecha del mensaje de Telegram",
            ),
            preserve_default=False,
        ),
    ]
