# Generated by Django 4.2.21 on 2025-07-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0006_telegrammessagemessagemodel_telegram_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessagemessagemodel",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemessagemodel",
            name="telegram_from",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="message",
        ),
        migrations.DeleteModel(
            name="TelegramChatModel",
        ),
        migrations.DeleteModel(
            name="TelegramFromModel",
        ),
        migrations.DeleteModel(
            name="TelegramMessageMessageModel",
        ),
        migrations.DeleteModel(
            name="TelegramMessageModel",
        ),
    ]
