# Generated by Django 4.2.21 on 2025-07-09 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0007_remove_telegrammessagemessagemodel_chat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="ID del chat de Telegram", unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "type",
                    models.CharField(
                        help_text="Tipo de chat (private, group, etc)", max_length=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramFromModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="ID de usuario de Telegram", unique=True
                    ),
                ),
                ("is_bot", models.BooleanField(default=False)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramMessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update_id",
                    models.BigIntegerField(
                        help_text="ID de actualización de Telegram", unique=True
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(help_text="ID del mensaje de Telegram"),
                ),
                (
                    "telegram_date",
                    models.IntegerField(
                        help_text="Fecha y hora del mensaje en Telegram",
                        verbose_name="Fecha del mensaje de Telegram",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Texto del mensaje de Telegram",
                        verbose_name="Texto del mensaje de Telegram",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Chat de Telegram al que pertenece el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.telegramchatmodel",
                        verbose_name="Chat de Telegram",
                    ),
                ),
                (
                    "telegram_from",
                    models.ForeignKey(
                        help_text="Usuario que envió el mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.telegramfrommodel",
                        verbose_name="Usuario de Telegram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Message",
                "verbose_name_plural": "Telegram Messages",
                "ordering": ["-telegram_date"],
            },
        ),
    ]
