# Generated by Django 4.2.21 on 2025-07-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0008_telegramchatmodel_telegramfrommodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="telegrammessagemodel",
            name="telegram_from",
        ),
        migrations.DeleteModel(
            name="TelegramChatModel",
        ),
        migrations.DeleteModel(
            name="TelegramFromModel",
        ),
        migrations.DeleteModel(
            name="TelegramMessageModel",
        ),
    ]
