# Generated by Django 4.2.21 on 2025-07-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0009_remove_telegrammessagemodel_chat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramChatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "update_id",
                    models.IntegerField(
                        help_text="ID de la actualización de Telegram",
                        verbose_name="ID de actualización",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Mensaje recibido del usuario",
                        verbose_name="Mensaje del usuario",
                    ),
                ),
                (
                    "message_id",
                    models.IntegerField(
                        help_text="ID del mensaje de Telegram",
                        verbose_name="ID del mensaje",
                    ),
                ),
                ("chat_id", models.IntegerField(help_text="ID del chat de Telegram")),
                (
                    "is_bot",
                    models.BooleanField(
                        default=False, help_text="Indica si el mensaje es de un bot"
                    ),
                ),
                (
                    "date",
                    models.IntegerField(
                        help_text="Fecha del mensaje en formato Unix timestamp",
                        verbose_name="Fecha del mensaje",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Nombre del usuario que envió el mensaje",
                        max_length=255,
                        verbose_name="Nombre del usuario",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Apellido del usuario que envió el mensaje",
                        max_length=255,
                        null=True,
                        verbose_name="Apellido del usuario",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Código de idioma del usuario",
                        max_length=2,
                        null=True,
                        verbose_name="Código de idioma",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
