# Generated by Django 4.2.21 on 2025-07-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0010_telegramchatmodel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="telegramchatmodel",
            unique_together={("chat_id", "message_id")},
        ),
    ]
