# Generated by Django 4.2.21 on 2025-07-09 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_agentmodel_analize_sentiment"),
        ("communication", "0011_alter_telegramchatmodel_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchatmodel",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente asociado a este chat de Telegram",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_chats",
                to="agents.agentmodel",
                verbose_name="Agente asociado",
            ),
        ),
        migrations.AddField(
            model_name="telegramchatmodel",
            name="error",
            field=models.CharField(
                blank=True,
                help_text="Mensaje de error si hubo un problema al procesar el mensaje",
                null=True,
                verbose_name="Mensaje de error",
            ),
        ),
    ]
