# Generated by Django 4.2.21 on 2025-07-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0012_telegramchatmodel_agent_telegramchatmodel_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchatmodel",
            name="telegram_communication",
            field=models.ForeignKey(
                blank=True,
                help_text="Modelo de comunicación de Telegram asociado a este chat",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_chats",
                to="communication.telegramcommunicationmodel",
                verbose_name="Modelo de comunicación de Telegram",
            ),
        ),
    ]
