# Generated by Django 4.2.21 on 2025-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0013_telegramchatmodel_telegram_communication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramchatmodel",
            name="chat_id",
            field=models.BigIntegerField(help_text="ID del chat de Telegram"),
        ),
        migrations.AlterField(
            model_name="telegramchatmodel",
            name="date",
            field=models.BigIntegerField(
                help_text="Fecha del mensaje en formato Unix timestamp",
                verbose_name="Fecha del mensaje",
            ),
        ),
        migrations.AlterField(
            model_name="telegramchatmodel",
            name="message_id",
            field=models.BigIntegerField(
                help_text="ID del mensaje de Telegram", verbose_name="ID del mensaje"
            ),
        ),
        migrations.AlterField(
            model_name="telegramchatmodel",
            name="update_id",
            field=models.BigIntegerField(
                help_text="ID de la actualización de Telegram",
                verbose_name="ID de actualización",
            ),
        ),
    ]
