# Generated by Django 5.2.1 on 2025-05-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0005_remove_chatmodel_content_contentchatmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actitude",
                    models.CharField(
                        choices=[
                            ("POSITIVO", "Positivo"),
                            ("NEGATIVO", "Negativo"),
                            ("NEUTRO", "Neutro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cause", models.TextField()),
                (
                    "content_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.contentchatmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
