# Generated by Django 5.2.1 on 2025-05-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('chats', '0005_remove_chatmodel_content_contentchatmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentimentModel',
            new_name='SentimentChatModel',
        ),
    ]
