# Generated by Django 4.2.21 on 2025-06-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_userprofile"),
        ("analysis", "0002_rename_sentimentmodel_sentimentchatmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "negative_tokens",
                    models.TextField(
                        help_text="Lista de tokens negativos, separados por comas."
                    ),
                ),
                (
                    "positive_tokens",
                    models.TextField(
                        help_text="Lista de tokens positivos, separados por comas."
                    ),
                ),
                (
                    "neutral_tokens",
                    models.TextField(
                        help_text="Lista de tokens neutrales, separados por comas."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_agents",
                        to="tenants.tenantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente de Sentimiento",
                "verbose_name_plural": "Agentes de Sentimiento",
                "ordering": ["-created_at"],
            },
        ),
    ]
