# Generated by Django 5.2.1 on 2025-05-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmodel",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
