# Generated by Django 5.2.1 on 2025-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_chatmodel_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmodel",
            name="content",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
