# Generated by Django 5.2.1 on 2025-05-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chatmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='content',
        ),
        migrations.CreateModel(
            name='ContentChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
