# Generated by Django 4.2.21 on 2025-06-05 15:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_remove_chatmodel_content_contentchatmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmodel",
            name="agent_instance",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
