# Generated by Django 4.2.21 on 2025-06-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_chatmodel_agent_instance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmodel",
            name="agent_instance",
        ),
    ]
