{
 "title": "Logger Status Dashboard",
 "time": { "from": "2025-07-09T13:25:12.010Z", "to": "2025-07-13T13:25:12.010Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Log Levels - Bar Chart",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE level\n    WHEN 10 THEN 'DEBUG'\n    WHEN 20 THEN 'INFO'\n    WHEN 30 THEN 'WARNING'\n    WHEN 40 THEN 'ERROR'\n    WHEN 50 THEN 'CRITICAL'\n    ELSE 'UNKNOWN'\n  END AS level_name,\n  COUNT(*) AS log_count\nFROM logger_statuslog \nGROUP BY level_name\nORDER BY log_count DESC;"
    }
   ]
  },
  {
   "title": "Log Levels - Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE level\r\n    WHEN 10 THEN 'DEBUG'\r\n    WHEN 20 THEN 'INFO'\r\n    WHEN 30 THEN 'WARNING'\r\n    WHEN 40 THEN 'ERROR'\r\n    WHEN 50 THEN 'CRITICAL'\r\n    ELSE 'UNKNOWN'\r\n  END AS level_name,\r\n  COUNT(*) AS log_count\r\nFROM logger_statuslog \r\nGROUP BY level_name\r\nORDER BY log_count DESC;"
    }
   ]
  },
  {
   "title": "Log Levels - Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "\nSELECT\n  CASE level\n    WHEN 10 THEN 'DEBUG'\n    WHEN 20 THEN 'INFO'\n    WHEN 30 THEN 'WARNING'\n    WHEN 40 THEN 'ERROR'\n    WHEN 50 THEN 'CRITICAL'\n    ELSE 'UNKNOWN'\n  END AS level_name,\n  COUNT(*) AS log_count\nFROM logger_statuslog \nGROUP BY level_name\nORDER BY log_count DESC;\n"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_logs FROM logger_statuslog;"
    }
   ]
  },
  {
   "title": "Most log levels for the past hour",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE level\r\n    WHEN 10 THEN 'DEBUG'\r\n    WHEN 20 THEN 'INFO'\r\n    WHEN 30 THEN 'WARNING'\r\n    WHEN 40 THEN 'ERROR'\r\n    WHEN 50 THEN 'CRITICAL'\r\n    ELSE 'UNKNOWN'\r\n  END AS level_name,\r\n  COUNT(*) AS log_count\r\nFROM logger_statuslog\r\nWHERE created_at >= NOW() - INTERVAL '1 hour'\r\nGROUP BY level\r\nORDER BY log_count DESC\r\nLIMIT 1;"
    }
   ]
  }
 ]
}