# Generated by Django 4.2.21 on 2025-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "NotSet"),
                            (20, "Info"),
                            (30, "Warning"),
                            (10, "Debug"),
                            (40, "Error"),
                            (50, "Fatal"),
                        ],
                        db_index=True,
                        default=40,
                    ),
                ),
                ("logger", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("pathname", models.CharField(max_length=100)),
                ("funcname", models.CharField(max_length=100)),
                ("lineno", models.IntegerField()),
                ("trace", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logging",
                "verbose_name_plural": "Logging",
                "ordering": ("-created_at",),
            },
        ),
    ]
