# Generated by Django 4.2.21 on 2025-06-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
                ('body', models.TextField(blank=True, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET')], default='GET', max_length=10)),
                ('username', models.CharField(blank=True, help_text='Nombre de usuario para autenticación básica, si es necesario', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='Contraseña para autenticación básica, si es necesario', max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, help_text='Clave de API para autenticación, si es necesario', max_length=255, null=True)),
                ('headers', models.JSONField(blank=True, help_text='Encabezados adicionales para la llamada a la API en formato JSON', null=True)),
                ('verify_ssl', models.BooleanField(default=True, help_text='Verificar el certificado SSL de la API, por defecto True')),
                ('timeout', models.IntegerField(default=30, help_text='Tiempo de espera para la llamada a la API en segundos, por defecto 30')),
                ('intructions', models.TextField(blank=True, help_text='Instrucciones opcionales para la llamada a la API', null=True)),
                ('tenant', models.ForeignKey(blank=True, default=None, help_text='Inquilino al que pertenece la llamada a la API', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='tenants.tenantmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
