# Generated by Django 4.2.21 on 2025-06-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apicallmodel",
            old_name="intructions",
            new_name="instructions",
        ),
    ]
